### ISSUE TITLE
Eclipse plugin naming

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#39]
Presently the name of the eclipse plugin after install is `itrace controller`.  Would we prefer this to say `iTrace Eclipse` or perhaps `iTrace Plugin`?

**Comment by shbonita** [comment]
iTrace Eclipse Plugin

**Comment by clptrsn** [comment]
Fixed with latest commit on development 4e477420266627c396c4f34c09463efac3717e7b

**Comment by dtg3** [comment]
The current installer is still showing the old plugin name. Once the installer reflects the change we will close this issue.

**Comment by dtg3** [comment]
@clptrsn The plugin is just called “itrace” in the open perspective menu. It needs to match the name of the plugin form (iTrace Eclipse Plugin).

**Comment by clptrsn** [comment]
Updated to the new name now

**Comment by dtg3** [comment]
Verified new name in perspective menu and settings. Updated instructions in Wiki to reflect the new naming.

**Comment by dtg3** [comment]
@clptrsn @Zealot-311 
The latest version of the plugin looks pretty good.
We still need to get the name to be iTrace Eclipse Plugin (instead of ITrace_Eclipse_Plugin).

**Comment by dtg3** [comment]
Fixed as of alpha 0.1.0 release
